
import type { TutorProfile, Testimonial, DemoSession, TuitionRequirement, MyClass, TutorPayment, TutorLead, TutorTransaction } from "@/types";

export const MOCK_TUTOR_PROFILES: TutorProfile[] = [
  {
    id: "t1",
    name: "Dr. Emily Carter",
    email: "emily.carter@example.com",
    role: "tutor",
    avatar: "https://picsum.photos/seed/emilycarter/128",
    subjects: ["Physics", "Mathematics", "Chemistry"],
    grade: "Doctorate Level",
    experience: "10+ years",
    hourlyRate: "1000", 
    bio: "PhD in Physics with a passion for demystifying complex scientific concepts for students of all levels. Specializes in advanced calculus and quantum mechanics. Believes in interactive learning and problem-solving approaches. Available for online sessions globally.",
    teachingMode: ["Online"],
    status: "Active",
    qualifications: ["PhD in Physics", "MSc in Applied Mathematics"],
    phone: "123-456-7890",
    isEmailVerified: true,
    isPhoneVerified: true,
    gender: "female",
    dateOfBirth: "1985-07-15T00:00:00.000Z",
    gradeLevelsTaught: ["College Level", "Doctorate Level"],
    boardsTaught: ["IB", "Cambridge", "A-Level"],
    preferredDays: ["Monday", "Wednesday", "Friday"],
    preferredTimeSlots: ["1600-1800", "1800-2000"],
    location: "Online",
    rating: 4.8,
  },
  {
    id: "t2",
    name: "John Adebayo",
    email: "john.adebayo@example.com",
    role: "tutor",
    avatar: "https://picsum.photos/seed/johnadebayo/128",
    subjects: ["English Literature", "History", "Creative Writing"],
    grade: "Master's Level",
    experience: "5-7 years",
    hourlyRate: "950", 
    bio: "MA in English Literature. Dedicated to fostering critical thinking and a love for the humanities. Experienced in preparing students for university entrance exams and essay writing. Enjoys incorporating classic and contemporary texts.",
    teachingMode: ["Offline (In-person)"],
    location: "Central City Library",
    status: "Active",
    qualifications: ["MA in English Literature", "BA in History"],
    phone: "987-654-3210",
    isEmailVerified: true,
    isPhoneVerified: false,
    gender: "male",
    dateOfBirth: "1990-03-22T00:00:00.000Z",
    gradeLevelsTaught: ["Grade 9-10", "Grade 11-12", "College Level"],
    boardsTaught: ["CBSE", "ICSE"],
    preferredDays: ["Tuesday", "Thursday", "Saturday"],
    preferredTimeSlots: ["1000-1200", "1400-1600"],
    rating: 4.5,
  },
  {
    id: "t3",
    name: "Sophia Chen",
    email: "sophia.chen@example.com",
    role: "tutor",
    avatar: "https://picsum.photos/seed/sophiachen/128",
    subjects: ["Computer Science", "Mathematics", "Web Development"],
    grade: "University Level",
    experience: "3-5 years",
    hourlyRate: "900", 
    bio: "Software engineer and CS graduate, specializing in Python, Java, and web technologies (React, Node.js). Passionate about mentoring aspiring developers and making coding accessible. Practical, project-based teaching style.",
    teachingMode: ["Online", "Offline (In-person)"],
    location: "Tech Park Co-working",
    status: "Active",
    qualifications: ["BSc in Computer Science", "Certified Web Developer"],
    phone: "123-456-7892",
    isEmailVerified: false,
    isPhoneVerified: true,
    gender: "female",
    dateOfBirth: "1995-11-10T00:00:00.000Z",
    gradeLevelsTaught: ["Grade 11-12", "College Level"],
    boardsTaught: ["State Board", "IB"],
    preferredDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    preferredTimeSlots: ["1800-2000", "2000-2200"],
    rating: 4.9,
  },
  {
    id: "t4",
    name: "David Miller",
    email: "david.miller@example.com",
    role: "tutor",
    avatar: "https://picsum.photos/seed/davidmiller/128",
    subjects: ["Biology", "Chemistry"],
    grade: "High School & College",
    experience: "7+ years",
    hourlyRate: "1000", 
    bio: "Former research scientist with extensive experience in tutoring high school and college biology and chemistry. Focuses on building strong foundational knowledge and lab skills. Can assist with AP and IB curricula.",
    teachingMode: ["Online"],
    status: "Inactive",
    qualifications: ["MSc in Biochemistry", "BSc in Biology"],
    phone: "123-456-7893",
    isEmailVerified: true,
    isPhoneVerified: true,
    gender: "male",
    dateOfBirth: "1982-01-05T00:00:00.000Z",
    gradeLevelsTaught: ["Grade 9-10", "Grade 11-12", "College Level"],
    boardsTaught: ["CBSE", "IGCSE", "Cambridge"],
    preferredDays: ["Weekends"],
    preferredTimeSlots: ["0800-1000", "1000-1200", "1200-1400"],
    location: "Online",
    rating: 4.7,
  },
  {
    id: "t5",
    name: "Linda Garcia",
    email: "linda.garcia@example.com",
    role: "tutor",
    avatar: "https://picsum.photos/seed/lindagarcia/128",
    subjects: ["Spanish", "French"],
    grade: "All Levels",
    experience: "3-5 years",
    hourlyRate: "800", 
    bio: "Native Spanish speaker, fluent in French. Passionate about language learning and cultural exchange. Offers conversational practice, grammar instruction, and exam preparation (DELE, DELF). Uses immersive techniques.",
    teachingMode: ["Offline (In-person)"],
    location: "Student's Home",
    status: "Active",
    qualifications: ["BA in Modern Languages", "TEFL Certified"],
    phone: "123-456-7894",
    isEmailVerified: true,
    isPhoneVerified: false,
    gender: "female",
    dateOfBirth: "1992-09-30T00:00:00.000Z",
    gradeLevelsTaught: ["Kindergarten", "Grade 1-5", "Grade 6-8", "Adult Learner"],
    boardsTaught: ["NIOS", "State Board"],
    preferredDays: ["Flexible"],
    preferredTimeSlots: ["Flexible"],
    rating: 4.6,
  },
  {
    id: "t6",
    name: "Mock Tutor General",
    email: "tutor@example.com",
    role: "tutor",
    avatar: "https://picsum.photos/seed/mocktutor/128",
    subjects: ["General Science", "Mathematics"],
    grade: "Middle School",
    experience: "2+ years",
    hourlyRate: "750",
    bio: "A friendly and patient tutor, skilled in making learning fun for middle school students. Focuses on building confidence and understanding core concepts.",
    teachingMode: ["Online", "Offline (In-person)"],
    location: "Online or Student's Home (Local Area)",
    status: "Active",
    qualifications: ["BSc in Education"],
    phone: "555-123-4567",
    isEmailVerified: true,
    isPhoneVerified: true,
    gender: "other",
    dateOfBirth: "1993-05-12T00:00:00.000Z",
    gradeLevelsTaught: ["Grade 6-8"],
    boardsTaught: ["CBSE", "State Board"],
    preferredDays: ["Tuesday", "Thursday", "Saturday"],
    preferredTimeSlots: ["1600-1800", "1000-1200"],
    rating: 4.2,
  }
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  { id: "testimonial1", name: "Sarah L. (Parent)", avatarSeed: "sarahparent", role: "Parent", text: "Tutorzila helped us find the perfect math tutor for our son. His grades have improved significantly!", rating: 5, date: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: "testimonial2", name: "David K. (Tutor)", avatarSeed: "davidtutor", role: "Tutor", text: "I love the flexibility of teaching on Tutorzila. I can set my own hours and connect with students who genuinely want to learn.", rating: 5, date: new Date(Date.now() - 86400000 * 12).toISOString() },
  { id: "testimonial3", name: "Maria P. (Parent)", avatarSeed: "mariaparent", role: "Parent", text: "The platform is user-friendly, and the quality of tutors is excellent. Highly recommend!", rating: 4, date: new Date(Date.now() - 86400000 * 20).toISOString() },
  { id: "testimonial4", name: "Ahmed R. (Tutor)", avatarSeed: "ahmedtutor", role: "Tutor", text: "A great way to find students and manage my tutoring business. The support team is also very responsive.", rating: 5, date: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: "testimonial5", name: "Jessica B. (Parent)", avatarSeed: "jessicaparent", role: "Parent", text: "Finding a qualified physics tutor was so easy with Tutorzila. My daughter is much more confident now.", rating: 5, date: new Date(Date.now() - 86400000 * 8).toISOString() },
];

export const MOCK_DEMO_SESSIONS: DemoSession[] = [
  {
    id: "demo1",
    tutorId: "t1",
    tutorName: "Dr. Emily Carter",
    tutorAvatarSeed: "emilycarter",
    studentName: "Rohan Sharma (Son)",
    subject: "Physics",
    gradeLevel: "Grade 11",
    board: "CBSE",
    date: new Date(Date.now() + 86400000 * 2).toISOString(),
    startTime: "04:00 PM",
    endTime: "04:30 PM",
    status: "Scheduled",
    joinLink: "https://zoom.us/j/123456789",
    mode: "Online",
    feedbackSubmitted: false,
  },
  {
    id: "demo2",
    tutorId: "t2", 
    tutorName: "John Adebayo",
    tutorAvatarSeed: "johnadebayo",
    studentName: "Priya Singh (Daughter)",
    subject: "English Literature",
    gradeLevel: "Grade 9",
    board: "ICSE",
    date: new Date(Date.now() + 86400000 * 5).toISOString(),
    startTime: "11:00 AM",
    endTime: "11:30 AM",
    status: "Scheduled",
    mode: "Offline (In-person)",
    feedbackSubmitted: false,
  },
  {
    id: "demo3",
    tutorId: "t3", 
    tutorName: "Sophia Chen",
    tutorAvatarSeed: "sophiachen",
    studentName: "Rohan Sharma (Son)",
    subject: "Computer Science",
    gradeLevel: "Grade 10",
    board: "IB",
    date: new Date(Date.now() + 86400000 * 7).toISOString(),
    startTime: "06:00 PM",
    endTime: "06:30 PM",
    status: "Requested",
    mode: "Online",
  },
  {
    id: "demo4",
    tutorId: "t1", 
    tutorName: "Dr. Emily Carter",
    tutorAvatarSeed: "emilycarter",
    studentName: "Priya Singh (Daughter)",
    subject: "Mathematics",
    gradeLevel: "Grade 10",
    board: "CBSE",
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    startTime: "03:00 PM",
    endTime: "03:30 PM",
    status: "Completed",
    mode: "Online",
    feedbackSubmitted: true,
  },
  {
    id: "demo5",
    tutorId: "t2", 
    tutorName: "John Adebayo",
    tutorAvatarSeed: "johnadebayo",
    studentName: "Rohan Sharma (Son)",
    subject: "History",
    gradeLevel: "Grade 7",
    board: "State Board",
    date: new Date(Date.now() - 86400000 * 10).toISOString(),
    startTime: "05:00 PM",
    endTime: "05:30 PM",
    status: "Cancelled",
    mode: "Offline (In-person)",
  },
  {
    id: "demo6_mock_tutor",
    tutorId: "t6", 
    tutorName: "Mock Tutor General",
    tutorAvatarSeed: "mocktutor",
    studentName: "Aarav Gupta (Son)",
    subject: "General Science",
    gradeLevel: "Grade 7",
    board: "CBSE",
    date: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(), 
    startTime: "03:00 PM",
    endTime: "03:30 PM",
    status: "Scheduled",
    joinLink: "#",
    mode: "Online",
  },
   {
    id: "demo7_john_upcoming",
    tutorId: "t2", 
    tutorName: "John Adebayo",
    tutorAvatarSeed: "johnadebayo",
    studentName: "Meera Iyer",
    subject: "History",
    gradeLevel: "Grade 10",
    board: "ICSE",
    date: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    startTime: "05:00 PM",
    endTime: "05:30 PM",
    status: "Scheduled",
    mode: "Online",
    joinLink: "https://example.com/join/john_meera"
  },
  {
    id: "demo8_emily_requested",
    tutorId: "t1", 
    tutorName: "Dr. Emily Carter",
    tutorAvatarSeed: "emilycarter",
    studentName: "Kevin D'Souza",
    subject: "Advanced Physics",
    gradeLevel: "Grade 12",
    board: "IB",
    date: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    startTime: "02:00 PM",
    endTime: "02:45 PM",
    status: "Requested",
    mode: "Online",
  },
  {
    id: "demo9_mock_tutor_today",
    tutorId: "t6", 
    tutorName: "Mock Tutor General",
    tutorAvatarSeed: "mocktutor",
    studentName: "Zara Khan",
    subject: "Mathematics",
    gradeLevel: "Grade 6",
    board: "State Board",
    date: new Date().toISOString(), 
    startTime: "05:30 PM",
    endTime: "06:00 PM",
    status: "Scheduled",
    joinLink: "#",
    mode: "Online",
  },
];

export const MOCK_CLASSES: MyClass[] = [
  { id: "c1", subject: "Advanced Algebra", tutorId: "t1", tutorName: "Dr. Emily Carter", tutorAvatarSeed: "emilycarter", studentName: "Rohan S.", mode: "Online", schedule: { days: ["Mon", "Wed"], time: "6:00 PM - 7:00 PM" }, status: "Ongoing", nextSession: new Date(Date.now() + 86400000 * 2).toISOString() },
  { id: "c2", subject: "Shakespearean Sonnets", tutorId: "t2", tutorName: "John Adebayo", tutorAvatarSeed: "johnadebayo", studentName: "Priya M.", mode: "Offline (In-person)", schedule: { days: ["Sat"], time: "10:00 AM - 12:00 PM" }, status: "Ongoing", nextSession: new Date(Date.now() + 86400000 * 4).toISOString() },
  { id: "c3", subject: "Introduction to Python", tutorId: "t3", tutorName: "Sophia Chen", tutorAvatarSeed: "sophiachen", studentName: "Rohan S.", mode: "Online", schedule: { days: ["Tues", "Thurs"], time: "7:00 PM - 8:00 PM" }, status: "Upcoming", startDate: new Date(Date.now() + 86400000 * 7).toISOString() },
  { id: "c4", subject: "Organic Chemistry Basics", tutorId: "t1", tutorName: "Dr. Emily Carter", tutorAvatarSeed: "emilycarter", studentName: "Aisha K.", mode: "Online", schedule: { days: ["Fri"], time: "5:00 PM - 6:30 PM" }, status: "Upcoming", startDate: new Date(Date.now() + 86400000 * 10).toISOString() },
  { id: "c5", subject: "World History: Ancient Civilizations", tutorId: "t2", tutorName: "John Adebayo", tutorAvatarSeed: "johnadebayo", studentName: "Rohan S.", mode: "Offline (In-person)", schedule: { days: ["Sun"], time: "2:00 PM - 4:00 PM" }, status: "Past", endDate: new Date(Date.now() - 86400000 * 15).toISOString() },
  { id: "c6", subject: "Web Development Fundamentals", tutorId: "t3", tutorName: "Sophia Chen", tutorAvatarSeed: "sophiachen", studentName: "Priya M.", mode: "Online", schedule: { days: ["Wed"], time: "6:30 PM - 8:00 PM" }, status: "Past", endDate: new Date(Date.now() - 86400000 * 30).toISOString() },
  { id: "c7", subject: "Calculus I", tutorId: "t1", tutorName: "Dr. Emily Carter", tutorAvatarSeed: "emilycarter", studentName: "Aisha K.", mode: "Online", schedule: { days: ["Mon"], time: "4:00 PM - 5:00 PM" }, status: "Cancelled" },
  { id: "c8_mock_tutor_upcoming", subject: "Mathematics Basics", tutorId: "t6", tutorName: "Mock Tutor General", tutorAvatarSeed: "mocktutor", studentName: "Vikram Rao", mode: "Online", schedule: { days: ["Fri"], time: "5:00 PM - 6:00 PM" }, status: "Upcoming", startDate: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString() }, 
  { id: "c9_mock_tutor_ongoing", subject: "Introduction to Science", tutorId: "t6", tutorName: "Mock Tutor General", tutorAvatarSeed: "mocktutor", studentName: "Sunita Patil", mode: "Online", schedule: { days: ["Wed"], time: "4:30 PM - 5:30 PM" }, status: "Ongoing", nextSession: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString() }, 
  { id: "c10_john_adebayo_upcoming", subject: "Historical Essay Writing", tutorId: "t2", tutorName: "John Adebayo", tutorAvatarSeed: "johnadebayo", studentName: "Arjun Menon", mode: "Offline (In-person)", schedule: { days: ["Mon"], time: "03:00 PM - 04:30 PM" }, status: "Upcoming", startDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString() }, 
];


export const MOCK_ALL_PARENT_REQUIREMENTS: TuitionRequirement[] = [
  {
    id: "current1",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["Mathematics", "Algebra"],
    gradeLevel: "Grade 6",
    scheduleDetails: "Looking for help with basic algebra and problem-solving skills. Student is a quick learner but needs to build confidence in exams.",
    preferredDays: ["Mon", "Wed"],
    preferredTimeSlots: ["1700-1900"],
    location: "Online",
    status: "open",
    postedAt: new Date("2025-05-01T10:00:00Z").toISOString(),
    additionalNotes: "Student is a quick learner but needs to build confidence in exams.",
    board: "CBSE",
    teachingMode: ["Online"],
    applicantsCount: 3,
    mockIsRecommended: true,
    mockIsAppliedByCurrentUser: false,
    mockIsShortlistedByCurrentUser: true,
  },
  {
    id: "current2",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["Science", "Physics"],
    gradeLevel: "Grade 8",
    scheduleDetails: "Needs assistance with Physics and Chemistry chapters for final exams. Focus on practical examples.",
    preferredDays: ["Tues", "Thurs"],
    preferredTimeSlots: ["1800-2000"],
    location: "Student's Home",
    status: "matched",
    postedAt: new Date("2025-05-05T14:30:00Z").toISOString(),
    additionalNotes: "Tutor selected (Ms. Anya Sharma), classes ongoing.",
    board: "ICSE",
    teachingMode: ["Offline (In-person)"],
    applicantsCount: 7,
    mockIsAppliedByCurrentUser: true,
    mockIsRecommended: false,
    mockIsShortlistedByCurrentUser: false,
  },
  {
    id: "past1",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["English", "Grammar"],
    gradeLevel: "Grade 5",
    scheduleDetails: "Focus on grammar and creative writing.",
    preferredDays: ["Saturday"],
    preferredTimeSlots: ["1000-1200"],
    location: "Tutor's Home",
    status: "closed",
    postedAt: new Date("2025-04-12T09:00:00Z").toISOString(),
    additionalNotes: "Found a tutor (Mr. Ramesh Kumar) but decided not to start classes at this time due to schedule conflicts. Requirement closed.",
    board: "State Board",
    teachingMode: ["Offline (In-person)"],
    applicantsCount: 5
  },
  {
    id: "past2",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["Hindi"],
    gradeLevel: "Grade 4",
    scheduleDetails: "Need help with reading and writing.",
    preferredDays: ["Flexible"],
    preferredTimeSlots: ["Flexible"],
    location: "Online",
    status: "closed",
    postedAt: new Date("2025-03-25T11:00:00Z").toISOString(),
    additionalNotes: "No suitable tutor was found for this requirement after reviewing 2 applications. Requirement closed.",
    board: "CBSE",
    teachingMode: ["Online"],
    applicantsCount: 2
  },
  {
    id: "current3-multisubject",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["Physics", "Chemistry", "Biology"],
    gradeLevel: "Grade 10",
    scheduleDetails: "Comprehensive science coaching for board exam preparation. Focus on conceptual clarity and numerical problems.",
    preferredDays: ["Mon", "Wed", "Fri"],
    preferredTimeSlots: ["1700-1900", "1900-2100"],
    location: "Online",
    status: "open",
    postedAt: new Date("2025-05-10T12:00:00Z").toISOString(),
    additionalNotes: "Looking for an experienced tutor with a proven track record.",
    board: "CBSE",
    teachingMode: ["Online"],
    applicantsCount: 1,
    mockIsShortlistedByCurrentUser: true,
    mockIsRecommended: true,
  },
  {
    id: "current4-languages",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["French", "German"],
    gradeLevel: "Adult Learner",
    scheduleDetails: "Beginner level conversational classes for travel purposes.",
    preferredDays: ["Saturday", "Sunday"],
    preferredTimeSlots: ["1000-1200"],
    location: "Tutor's Home",
    status: "open",
    postedAt: new Date("2025-05-12T15:00:00Z").toISOString(),
    additionalNotes: "Emphasis on practical communication skills.",
    board: "Other",
    teachingMode: ["Offline (In-person)"],
    applicantsCount: 0,
    mockIsRecommended: true,
  },
  {
    id: "past3-hybrid",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["Computer Science", "Mathematics"],
    gradeLevel: "Grade 12",
    scheduleDetails: "Advanced programming concepts and competitive exam math.",
    preferredDays: ["Flexible"],
    preferredTimeSlots: ["Evening Hours"],
    location: "Student's Home",
    status: "closed",
    postedAt: new Date("2025-02-15T18:00:00Z").toISOString(),
    additionalNotes: "Classes completed successfully with Tutor XYZ. Student scored well. Requirement closed.",
    board: "IB",
    teachingMode: ["Online", "Offline (In-person)"],
    applicantsCount: 6
  },
  {
    id: "other1", 
    parentId: "p2",
    parentName: "Bob Johnson",
    subject: ["Physics", "Chemistry"],
    gradeLevel: "Grade 11-12",
    scheduleDetails: "Needs urgent help for upcoming competitive exams. Strong fundamentals required.",
    preferredDays: ["Saturday", "Sunday"],
    preferredTimeSlots: ["0800-1000"],
    location: "Student's Home",
    status: "open",
    postedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    board: "ICSE",
    teachingMode: ["Offline (In-person)"],
    applicantsCount: 3,
    additionalNotes: "Looking for experienced tutors only.",
    mockIsRecommended: true,
    mockIsAppliedByCurrentUser: true, 
  },
   {
    id: "alice_open_1",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["History", "Geography"],
    gradeLevel: "Grade 7",
    scheduleDetails: "Need a tutor to make social studies engaging and help with map work.",
    preferredDays: ["Tues", "Fri"],
    preferredTimeSlots: ["1600-1800"],
    location: "Online",
    status: "open",
    postedAt: new Date("2025-05-15T09:00:00Z").toISOString(),
    additionalNotes: "Previous tutor was not very interactive.",
    board: "CBSE",
    teachingMode: ["Online"],
    applicantsCount: 0,
    mockIsAppliedByCurrentUser: false,
    mockIsRecommended: false,
    mockIsShortlistedByCurrentUser: false,
  },
  {
    id: "alice_matched_1",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["Art", "Music (Piano)"],
    gradeLevel: "Grade 3",
    scheduleDetails: "Looking for a patient tutor for basic art skills and beginner piano lessons.",
    preferredDays: ["Saturday"],
    preferredTimeSlots: ["1100-1300"],
    location: "Tutor's Home",
    status: "matched",
    postedAt: new Date("2025-04-20T16:00:00Z").toISOString(),
    additionalNotes: "Tutor Clara B. selected. Demos completed.",
    board: "IGCSE",
    teachingMode: ["Offline (In-person)"],
    applicantsCount: 4,
    mockIsShortlistedByCurrentUser: true,
    mockIsRecommended: false,
    mockIsAppliedByCurrentUser: false,
  },
  {
    id: "alice_closed_1",
    parentId: "p1",
    parentName: "Alice Smith",
    subject: ["Coding (Python)"],
    gradeLevel: "Grade 9",
    scheduleDetails: "Introduction to Python programming for a beginner.",
    preferredDays: ["Weekends"],
    preferredTimeSlots: ["1400-1600"],
    location: "Online",
    status: "closed",
    postedAt: new Date("2025-01-10T10:00:00Z").toISOString(),
    additionalNotes: "Successfully completed a 3-month Python basics course with Tutor Mike. Requirement closed.",
    board: "CBSE",
    teachingMode: ["Online"],
    applicantsCount: 2,
    mockIsRecommended: false,
    mockIsAppliedByCurrentUser: false,
    mockIsShortlistedByCurrentUser: false,
  }
];

export const MOCK_TUTOR_PAYMENTS: TutorPayment[] = [
  {
    id: "pay1",
    tutorId: "t2", 
    studentName: "Priya M.",
    subject: "English Literature",
    amount: 7600, 
    hourlyRate: 950,
    totalHours: 8,
    totalSessions: 8,
    fromDate: new Date(2025, 3, 1).toISOString(), 
    toDate: new Date(2025, 3, 30).toISOString(),   
    status: "Pending",
  },
  {
    id: "pay2",
    tutorId: "t1", 
    studentName: "Rohan S.",
    subject: "Advanced Algebra",
    amount: 8000, 
    hourlyRate: 1000,
    totalHours: 8,
    totalSessions: 8,
    fromDate: new Date(2025, 3, 1).toISOString(), 
    toDate: new Date(2025, 3, 30).toISOString(),   
    status: "Paid",
    paymentDate: new Date(2025, 4, 2).toISOString(), 
  },
  {
    id: "pay3",
    tutorId: "t6", 
    studentName: "Sunita Patil",
    subject: "Introduction to Science",
    amount: 3000, 
    hourlyRate: 750,
    totalHours: 4,
    totalSessions: 4,
    fromDate: new Date(2025, 4, 1).toISOString(), 
    toDate: new Date(2025, 4, 31).toISOString(),   
    status: "Pending",
  },
   {
    id: "pay4",
    tutorId: "t2", 
    studentName: "Arjun Menon",
    subject: "Historical Essay Writing",
    amount: 3800, 
    hourlyRate: 950,
    totalHours: 6, 
    totalSessions: 4,
    fromDate: new Date(new Date().getFullYear(), new Date().getMonth() -1, 1).toISOString(), 
    toDate: new Date(new Date().getFullYear(), new Date().getMonth() -1, 28).toISOString(),
    status: "Paid",
    paymentDate: new Date(new Date().getFullYear(), new Date().getMonth(), 2).toISOString(), 
  },
  {
    id: "pay5",
    tutorId: "t6", 
    studentName: "Vikram Rao",
    subject: "Mathematics Basics",
    amount: 1500, 
    hourlyRate: 750,
    totalHours: 2,
    totalSessions: 2,
    fromDate: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString(), 
    toDate: new Date(new Date().getFullYear(), new Date().getMonth(), 15).toISOString(),
    status: "Pending",
  },
];

export const MOCK_TUTOR_LEADS: TutorLead[] = [
  {
    id: "lead1",
    tutorId: "t2", 
    parentName: "Ananya Sharma",
    parentAvatarSeed: "ananya",
    email: "ananya.sharma@example.com",
    phone: "+919876543210",
    contactedOn: new Date(Date.now() - 86400000 * 3).toISOString(), 
    messagesCount: 5,
    lastMessageSnippet: "Yes, I'm interested in discussing history tuitions...",
    status: "Contacted",
    enquirySubject: "History",
    enquiryGrade: "Grade 10",
    leadsConsumed: 1,
  },
  {
    id: "lead2",
    tutorId: "t6", 
    parentName: "Rajesh Kumar",
    parentAvatarSeed: "rajesh",
    email: "rajesh.kumar@example.com",
    phone: "+919988776655",
    contactedOn: new Date(Date.now() - 86400000 * 1).toISOString(), 
    messagesCount: 2,
    lastMessageSnippet: "Can you teach Grade 7 Math?",
    status: "New",
    enquirySubject: "Mathematics",
    enquiryGrade: "Grade 7",
    leadsConsumed: 2,
  },
  {
    id: "lead3",
    tutorId: "t2", 
    parentName: "Priya Singh", 
    parentAvatarSeed: "priyasingh",
    email: "priya.s@example.com",
    phone: "+919123456789",
    contactedOn: new Date(Date.now() - 86400000 * 7).toISOString(), 
    messagesCount: 12,
    lastMessageSnippet: "Thank you for the demo! We'll be in touch.",
    status: "Interested",
    enquirySubject: "English Literature",
    enquiryGrade: "Grade 9",
    leadsConsumed: 1,
  },
  {
    id: "lead4",
    tutorId: "t6", 
    parentName: "Amit Patel",
    parentAvatarSeed: "amitpatel",
    email: "amit.p@example.com",
    phone: "+919777777777",
    contactedOn: new Date(Date.now() - 86400000 * 5).toISOString(), 
    messagesCount: 1,
    lastMessageSnippet: "Sent initial inquiry.",
    status: "New",
    enquirySubject: "General Science",
    enquiryGrade: "Grade 6",
    leadsConsumed: 0, 
  },
];

export const MOCK_TUTOR_TRANSACTIONS: TutorTransaction[] = [
  { id: "txn1", tutorId: "t2", type: "Credit", mode: "Wallet", amount: 500, date: new Date(Date.now() - 86400000 * 2).toISOString(), summary: "Lead purchase credits" },
  { id: "txn2", tutorId: "t2", type: "Debit", mode: "Wallet", amount: 5, date: new Date(Date.now() - 86400000 * 1).toISOString(), summary: "Lead consumed for Ananya Sharma" },
  { id: "txn3", tutorId: "t6", type: "Credit", mode: "Online", amount: 2000, date: new Date(Date.now() - 86400000 * 5).toISOString(), summary: "Payment received from Sunita Patil" },
  { id: "txn4", tutorId: "t6", type: "Debit", mode: "Wallet", amount: 2, date: new Date(Date.now() - 86400000 * 3).toISOString(), summary: "Lead consumed for Rajesh Kumar" },
  { id: "txn5", tutorId: "t2", type: "Credit", mode: "Cash", amount: 3800, date: new Date().toISOString(), summary: "Payment collected from Arjun Menon" },
];
