
import type { TutorProfile, Testimonial } from "@/types";

export const MOCK_TUTOR_PROFILES: TutorProfile[] = [
  { 
    id: "t1", 
    name: "Dr. Emily Carter", 
    email: "emily.carter@example.com", 
    role: "tutor", 
    avatar: "https://picsum.photos/seed/emilycarter/128", 
    subjects: ["Physics", "Mathematics", "Chemistry"], 
    grade: "Doctorate Level", 
    experience: "10+ years", 
    hourlyRate: "5000", 
    bio: "PhD in Physics with a passion for demystifying complex scientific concepts for students of all levels. Specializes in advanced calculus and quantum mechanics. Believes in interactive learning and problem-solving approaches. Available for online sessions globally.", 
    teachingMode: ["Online"], 
    status: "Active", 
    qualifications: ["PhD in Physics", "MSc in Applied Mathematics"], 
    phone: "123-456-7890", 
    isEmailVerified: true, 
    isPhoneVerified: true,
    gender: "female",
    dateOfBirth: "1985-07-15T00:00:00.000Z",
    gradeLevelsTaught: ["College Level", "Doctorate Level"],
    boardsTaught: ["IB", "A-Level"],
    preferredDays: ["Monday", "Wednesday", "Friday"],
    preferredTimeSlots: ["1600-1800", "1800-2000"]
  },
  { 
    id: "t2", 
    name: "John Adebayo", 
    email: "john.adebayo@example.com", 
    role: "tutor", 
    avatar: "https://picsum.photos/seed/johnadebayo/128", 
    subjects: ["English Literature", "History", "Creative Writing"], 
    grade: "Master's Level", 
    experience: "5-7 years", 
    hourlyRate: "4000", 
    bio: "MA in English Literature. Dedicated to fostering critical thinking and a love for the humanities. Experienced in preparing students for university entrance exams and essay writing. Enjoys incorporating classic and contemporary texts.", 
    teachingMode: ["In-person"], 
    location: "Central City Library",
    status: "Active", 
    qualifications: ["MA in English Literature", "BA in History"], 
    phone: "987-654-3210", 
    isEmailVerified: true, 
    isPhoneVerified: false,
    gender: "male",
    dateOfBirth: "1990-03-22T00:00:00.000Z",
    gradeLevelsTaught: ["Grade 9-10", "Grade 11-12", "College Level"],
    boardsTaught: ["CBSE", "ICSE"],
    preferredDays: ["Tuesday", "Thursday", "Saturday"],
    preferredTimeSlots: ["1000-1200", "1400-1600"]
  },
  { 
    id: "t3", 
    name: "Sophia Chen", 
    email: "sophia.chen@example.com", 
    role: "tutor", 
    avatar: "https://picsum.photos/seed/sophiachen/128", 
    subjects: ["Computer Science", "Mathematics", "Web Development"], 
    grade: "University Level", 
    experience: "3-5 years", 
    hourlyRate: "4500", 
    bio: "Software engineer and CS graduate, specializing in Python, Java, and web technologies (React, Node.js). Passionate about mentoring aspiring developers and making coding accessible. Practical, project-based teaching style.", 
    teachingMode: ["Online", "In-person"], 
    location: "Tech Park Co-working",
    status: "Active", 
    qualifications: ["BSc in Computer Science", "Certified Web Developer"], 
    phone: "123-456-7892", 
    isEmailVerified: false, 
    isPhoneVerified: true,
    gender: "female",
    dateOfBirth: "1995-11-10T00:00:00.000Z",
    gradeLevelsTaught: ["Grade 11-12", "College Level"],
    boardsTaught: ["State Board", "IB"],
    preferredDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    preferredTimeSlots: ["1800-2000", "2000-2200"]
  },
  { 
    id: "t4", 
    name: "David Miller", 
    email: "david.miller@example.com", 
    role: "tutor", 
    avatar: "https://picsum.photos/seed/davidmiller/128", 
    subjects: ["Biology", "Chemistry"], 
    grade: "High School & College", 
    experience: "7+ years", 
    hourlyRate: "4800", 
    bio: "Former research scientist with extensive experience in tutoring high school and college biology and chemistry. Focuses on building strong foundational knowledge and lab skills. Can assist with AP and IB curricula.", 
    teachingMode: ["Online"], 
    status: "Inactive", 
    qualifications: ["MSc in Biochemistry", "BSc in Biology"], 
    phone: "123-456-7893", 
    isEmailVerified: true, 
    isPhoneVerified: true,
    gender: "male",
    dateOfBirth: "1982-01-05T00:00:00.000Z",
    gradeLevelsTaught: ["Grade 9-10", "Grade 11-12", "College Level"],
    boardsTaught: ["CBSE", "IGCSE", "AP"],
    preferredDays: ["Weekends"],
    preferredTimeSlots: ["0800-1000", "1000-1200", "1200-1400"]
  },
  { 
    id: "t5", 
    name: "Linda Garcia", 
    email: "linda.garcia@example.com", 
    role: "tutor", 
    avatar: "https://picsum.photos/seed/lindagarcia/128", 
    subjects: ["Spanish", "French"], 
    grade: "All Levels", 
    experience: "3-5 years", 
    hourlyRate: "3500", 
    bio: "Native Spanish speaker, fluent in French. Passionate about language learning and cultural exchange. Offers conversational practice, grammar instruction, and exam preparation (DELE, DELF). Uses immersive techniques.", 
    teachingMode: ["In-person"], 
    location: "Student's Home",
    status: "Active", 
    qualifications: ["BA in Modern Languages", "TEFL Certified"], 
    phone: "123-456-7894", 
    isEmailVerified: true, 
    isPhoneVerified: false,
    gender: "female",
    dateOfBirth: "1992-09-30T00:00:00.000Z",
    gradeLevelsTaught: ["Kindergarten", "Grade 1-5", "Grade 6-8", "Adult Learner"],
    boardsTaught: ["All Boards"], // Example of a field that might be a string or array
    preferredDays: ["Flexible"],
    preferredTimeSlots: ["Flexible"]
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  { id: "testimonial1", name: "Sarah L. (Parent)", avatarSeed: "sarahparent", role: "Parent", text: "Tutorzila helped us find the perfect math tutor for our son. His grades have improved significantly!", rating: 5, date: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: "testimonial2", name: "David K. (Tutor)", avatarSeed: "davidtutor", role: "Tutor", text: "I love the flexibility of teaching on Tutorzila. I can set my own hours and connect with students who genuinely want to learn.", rating: 5, date: new Date(Date.now() - 86400000 * 12).toISOString() },
  { id: "testimonial3", name: "Maria P. (Parent)", avatarSeed: "mariaparent", role: "Parent", text: "The platform is user-friendly, and the quality of tutors is excellent. Highly recommend!", rating: 4, date: new Date(Date.now() - 86400000 * 20).toISOString() },
  { id: "testimonial4", name: "Ahmed R. (Tutor)", avatarSeed: "ahmedtutor", role: "Tutor", text: "A great way to find students and manage my tutoring business. The support team is also very responsive.", rating: 5, date: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: "testimonial5", name: "Jessica B. (Parent)", avatarSeed: "jessicaparent", role: "Parent", text: "Finding a qualified physics tutor was so easy with Tutorzila. My daughter is much more confident now.", rating: 5, date: new Date(Date.now() - 86400000 * 8).toISOString() },
];


